"""GET4 segmentation-uncertainty reports (frontend: Uncertainty (GET4) tab)."""

import json

from fastapi import APIRouter, HTTPException, Query

from ..paths import GET4_DATA_DIR

router = APIRouter()
GET4_DETECTORS = {"BSE", "ETD", "INLENS", "SE", "TLD", "CBS"}


@router.get("/batches/{batch_id}/uncertainty")
def get_batch_uncertainty(batch_id: str, detector: str = Query(default="BSE")):
    """Return a generated GET4 batch report for one batch and detector."""
    if not batch_id.isdigit():
        raise HTTPException(404, f"Unknown image batch {batch_id}")
    detector_name = detector.upper()
    if detector_name not in GET4_DETECTORS:
        raise HTTPException(422, f"Unsupported detector {detector}")

    report_path = GET4_DATA_DIR / f"batch_{batch_id}" / detector_name / "batch_uncertainty.json"
    if not report_path.is_file():
        raise HTTPException(
            404,
            f"No GET4 report found for batch {batch_id} detector {detector_name}; "
            "run python -m analysis.get4 --project to generate reports",
        )
    try:
        return json.loads(report_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise HTTPException(500, f"GET4 report for batch {batch_id} is invalid JSON") from error


@router.get("/batches/{batch_id}/analysis-report")
def get_batch_analysis_report(batch_id: str, detector: str = Query(default="BSE")):
    """Return the website-ready KPI and evidence report generated by GET4."""
    if not batch_id.isdigit():
        raise HTTPException(404, f"Unknown image batch {batch_id}")
    detector_name = detector.upper()
    if detector_name not in GET4_DETECTORS:
        raise HTTPException(422, f"Unsupported detector {detector}")

    report_path = GET4_DATA_DIR / f"batch_{batch_id}" / detector_name / "analysis_report.json"
    if not report_path.is_file():
        raise HTTPException(
            404,
            f"No GET4 analysis report found for batch {batch_id} detector {detector_name}; "
            "run python -m analysis.get4 --project to generate reports",
        )
    try:
        return json.loads(report_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise HTTPException(500, f"GET4 analysis report for batch {batch_id} is invalid JSON") from error
