"""GET4 segmentation-uncertainty reports (frontend: Uncertainty (GET4) tab), for batches 1-3 and the unknown batch."""

import json
from pathlib import Path

from fastapi import APIRouter, HTTPException, Query

from ..paths import GET4_DATA_DIR, UNKNOWN_BATCH

router = APIRouter()
GET4_DETECTORS = {"BSE", "ETD", "INLENS", "SE", "TLD", "CBS"}


def _report_path(batch_id: str, detector: str, filename: str) -> tuple[Path, str]:
    """GET4 output file for one batch and detector: data/processed/get4/{batch_N|unknown}/{DETECTOR}/filename.
    The unknown batch's reports are written by the unknown-batch analysis job."""
    if batch_id == UNKNOWN_BATCH:
        folder, regenerate = UNKNOWN_BATCH, "re-run the unknown-batch analysis from the Upload tab"
    elif batch_id.isdigit():
        folder, regenerate = f"batch_{batch_id}", "run python -m analysis.get4 --project to generate reports"
    else:
        raise HTTPException(404, f"Unknown image batch {batch_id}")
    detector_name = detector.upper()
    if detector_name not in GET4_DETECTORS:
        raise HTTPException(422, f"Unsupported detector {detector}")
    return GET4_DATA_DIR / folder / detector_name / filename, regenerate


def _read_report(path: Path, missing: str, invalid: str) -> dict:
    if not path.is_file():
        raise HTTPException(404, missing)
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise HTTPException(500, invalid) from error


@router.get("/batches/{batch_id}/uncertainty")
def get_batch_uncertainty(batch_id: str, detector: str = Query(default="BSE")):
    """Return a generated GET4 batch report for one batch and detector."""
    path, regenerate = _report_path(batch_id, detector, "batch_uncertainty.json")
    return _read_report(path, f"No GET4 report found for batch {batch_id} detector {detector.upper()}; {regenerate}",
                        f"GET4 report for batch {batch_id} is invalid JSON")


@router.get("/batches/{batch_id}/analysis-report")
def get_batch_analysis_report(batch_id: str, detector: str = Query(default="BSE")):
    """Return the website-ready KPI and evidence report generated by GET4."""
    path, regenerate = _report_path(batch_id, detector, "analysis_report.json")
    return _read_report(path, f"No GET4 analysis report found for batch {batch_id} detector {detector.upper()}; "
                              f"{regenerate}",
                        f"GET4 analysis report for batch {batch_id} is invalid JSON")
