"""Per-batch KPI reports and overlays from analysis.kpis (frontend: KPI report tab)."""

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from ..batches import is_image_batch, read_kpi_json
from ..paths import KPI_DATA_DIR, LOCATION_ID_PATTERN

router = APIRouter()


@router.get("/kpi-reports/summary")
def get_kpi_summary() -> dict:
    """Headline KPIs of every analysed reference batch, for side-by-side comparison."""
    return read_kpi_json(KPI_DATA_DIR / "summary.json", "No KPI summary found")


@router.get("/batches/{batch_id}/kpi-report")
def get_kpi_report(batch_id: str) -> dict:
    """Detailed per-batch KPI report generated by analysis.kpis."""
    if not is_image_batch(batch_id):
        raise HTTPException(404, f"Unknown image batch {batch_id}")
    return read_kpi_json(
        KPI_DATA_DIR / f"batch_{batch_id}" / "report.json", f"No KPI report found for batch {batch_id}"
    )


@router.get("/batches/{batch_id}/kpi-report/overlays/{location_id}")
def get_kpi_overlay(batch_id: str, location_id: str) -> FileResponse:
    """Segmentation overlay JPEG for one analysed location."""
    if not is_image_batch(batch_id) or not LOCATION_ID_PATTERN.fullmatch(location_id):
        raise HTTPException(404, "Unknown overlay")
    path = KPI_DATA_DIR / f"batch_{batch_id}" / "overlays" / f"{location_id}.jpg"
    if not path.is_file():
        raise HTTPException(404, f"No overlay for location {location_id} in batch {batch_id}")
    return FileResponse(path, media_type="image/jpeg", headers={"Cache-Control": "public, max-age=3600"})
