"""FastAPI routes for listing material batches and retrieving their analysis."""

import json
import re
from io import BytesIO
from pathlib import Path
from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, Response
from PIL import Image
from .schemas import Analysis, BatchSummary

app = FastAPI(title="EM QC API")

# Allow the local Vite page and other frontends to call this API during development.
# For a public production deployment, replace "*" with the approved frontend origin.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], 
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)

MOCK_DIR = Path(__file__).parent / "mock"
RAW_DATA_DIR = Path(__file__).resolve().parents[2] / "data" / "raw"
GET4_DATA_DIR = Path(__file__).resolve().parents[2] / "data" / "processed" / "get4"
KPI_DATA_DIR = Path(__file__).resolve().parents[2] / "data" / "processed" / "batch_kpis"
FIELD_DATA_DIR = Path(__file__).resolve().parents[2] / "data" / "processed" / "fields"
LOCATION_ID_PATTERN = re.compile(r"^[A-Za-z0-9]+$")
GET4_DETECTORS = {"BSE", "ETD", "INLENS", "SE", "TLD", "CBS"}
IMAGE_NAME_PATTERN = re.compile(
    r"^img_(?P<specimen>.+?)_(?P<filter>BSE|ETD|Inlens|SE)(?:\s+\(\d+\))?\.tif$",
    re.IGNORECASE,
)

def load_mock(batch_id: str) -> dict:
    """Load one batch's sample analysis JSON, or return HTTP 404 if it is unknown."""
    path = MOCK_DIR / f"{batch_id}.json"
    if not path.exists():
        raise HTTPException(404, f"Unknown batch {batch_id}")
    return json.loads(path.read_text(encoding="utf-8"))


def get_batch_image_directory(batch_id: str) -> Path:
    """Return a valid local raw-image directory for a numeric batch ID."""
    if not batch_id.isdigit():
        raise HTTPException(404, f"Unknown image batch {batch_id}")
    directory = RAW_DATA_DIR / f"batch_{batch_id}"
    if not directory.is_dir():
        raise HTTPException(404, f"Image directory for batch {batch_id} was not found")
    return directory


def find_batch_image(batch_id: str, image_name: str) -> Path:
    """Resolve an image name only when it matches an indexed file in its batch."""
    directory = get_batch_image_directory(batch_id)
    for path in directory.iterdir():
        if path.is_file() and path.name == image_name and IMAGE_NAME_PATTERN.fullmatch(path.name):
            return path
    raise HTTPException(404, f"Unknown image {image_name} in batch {batch_id}")


@app.get("/batches", response_model=list[BatchSummary])
def list_batches():
    """Return one compact summary for every JSON batch in the mock-data folder."""
    return [load_mock(p.stem) for p in sorted(MOCK_DIR.glob("*.json"))]

@app.get("/batches/{batch_id}/analysis", response_model=Analysis)
def get_analysis(batch_id: str):
    """Return the full analysis record for the requested batch ID."""
    return load_mock(batch_id)


@app.get("/batches/{batch_id}/uncertainty")
def get_batch_uncertainty(batch_id: str, detector: str = Query(default="BSE")):
    """Return a generated GET4 batch report for one batch and detector."""
    if not batch_id.isdigit():
        raise HTTPException(404, f"Unknown image batch {batch_id}")
    detector_name = detector.upper()
    if detector_name not in GET4_DETECTORS:
        raise HTTPException(422, f"Unsupported detector {detector}")

    report_path = GET4_DATA_DIR / f"batch_{batch_id}" / detector_name / "batch_uncertainty.json"
    if not report_path.is_file():
        raise HTTPException(
            404,
            f"No GET4 report found for batch {batch_id} detector {detector_name}; "
            "run GET4.py --project to generate reports",
        )
    try:
        return json.loads(report_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise HTTPException(500, f"GET4 report for batch {batch_id} is invalid JSON") from error


@app.get("/batches/{batch_id}/analysis-report")
def get_batch_analysis_report(batch_id: str, detector: str = Query(default="BSE")):
    """Return the website-ready KPI and evidence report generated by GET4."""
    if not batch_id.isdigit():
        raise HTTPException(404, f"Unknown image batch {batch_id}")
    detector_name = detector.upper()
    if detector_name not in GET4_DETECTORS:
        raise HTTPException(422, f"Unsupported detector {detector}")

    report_path = GET4_DATA_DIR / f"batch_{batch_id}" / detector_name / "analysis_report.json"
    if not report_path.is_file():
        raise HTTPException(
            404,
            f"No GET4 analysis report found for batch {batch_id} detector {detector_name}; "
            "run GET4.py --project to generate reports",
        )
    try:
        return json.loads(report_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise HTTPException(500, f"GET4 analysis report for batch {batch_id} is invalid JSON") from error


def read_kpi_json(path: Path, missing: str) -> dict:
    """Read a batch_kpis.py output file, mapping absent or corrupt files to clear HTTP errors."""
    if not path.is_file():
        raise HTTPException(404, f"{missing}; run batch_kpis.py to generate KPI reports")
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as error:
        raise HTTPException(500, f"{path.name} is invalid JSON") from error


@app.get("/kpi-reports/summary")
def get_kpi_summary():
    """Headline KPIs of every analysed reference batch, for side-by-side comparison."""
    return read_kpi_json(KPI_DATA_DIR / "summary.json", "No KPI summary found")


@app.get("/batches/{batch_id}/kpi-report")
def get_kpi_report(batch_id: str):
    """Detailed per-batch KPI report generated by batch_kpis.py."""
    if not batch_id.isdigit():
        raise HTTPException(404, f"Unknown image batch {batch_id}")
    return read_kpi_json(KPI_DATA_DIR / f"batch_{batch_id}" / "report.json",
                         f"No KPI report found for batch {batch_id}")


@app.get("/batches/{batch_id}/kpi-report/overlays/{location_id}")
def get_kpi_overlay(batch_id: str, location_id: str):
    """Segmentation overlay JPEG for one analysed location."""
    if not batch_id.isdigit() or not LOCATION_ID_PATTERN.fullmatch(location_id):
        raise HTTPException(404, "Unknown overlay")
    path = KPI_DATA_DIR / f"batch_{batch_id}" / "overlays" / f"{location_id}.jpg"
    if not path.is_file():
        raise HTTPException(404, f"No overlay for location {location_id} in batch {batch_id}")
    return FileResponse(path, media_type="image/jpeg", headers={"Cache-Control": "public, max-age=3600"})


@app.get("/batches/{batch_id}/images")
def list_batch_images(batch_id: str):
    """List local TIFF views grouped by the field of view they show.

    Filename codes do not identify fields, so when field_matching.py has produced a manifest
    covering exactly these files, its image-matched fields are used. Otherwise the views fall
    back to filename-code groups, marked with grouping "filename" so the UI can warn."""
    directory = get_batch_image_directory(batch_id)
    files = {}
    for path in sorted(directory.iterdir()):
        match = IMAGE_NAME_PATTERN.fullmatch(path.name)
        if path.is_file() and match:
            files[path.name] = match
    manifest_path = FIELD_DATA_DIR / f"batch_{batch_id}.json"
    if manifest_path.is_file():
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
            listed = {view["filename"] for field in manifest["fields"] for view in field["views"]}
        except (json.JSONDecodeError, KeyError, TypeError):
            listed = None
        if listed == set(files):
            return [
                {
                    "specimen_id": field.get("location", field["field_id"]),
                    "field_id": field["field_id"],
                    "location_recovered": field.get("location_recovered"),
                    "location_alternatives": field.get("location_alternatives", []),
                    "grouping": "matched",
                    "match_confidence": field["confidence"],
                    "filename_codes": field["filename_codes"],
                    # "filter" stays the filename label (other code keys on it); "detector" is the
                    # detector identified from the image itself.
                    "images": [
                        {
                            "filter": files[view["filename"]].group("filter"),
                            "filename": view["filename"],
                            "detector": view.get("detector"),
                            "display_name": view.get("display_name"),
                            "label_matches_image": view.get("label_matches_image"),
                            "detector_confidence": view.get("detector_confidence"),
                        }
                        for view in sorted(
                            field["views"],
                            key=lambda v: {"BSE": 0, "InLens": 1, "ETD": 2}.get(v.get("detector"), 3),
                        )
                    ],
                }
                for field in sorted(manifest["fields"], key=lambda f: f.get("location", f["field_id"]))
            ]
    groups: dict[str, list[dict[str, str]]] = {}
    for name, match in files.items():
        groups.setdefault(match.group("specimen"), []).append(
            {"filter": match.group("filter"), "filename": name}
        )
    return [
        {"specimen_id": specimen_id, "grouping": "filename", "images": images}
        for specimen_id, images in sorted(groups.items())
    ]


@app.get("/batches/{batch_id}/images/{image_name}")
def get_batch_image(
    batch_id: str,
    image_name: str,
    download: bool = Query(default=False),
):
    """Serve a browser-friendly JPEG preview or the original TIFF download."""
    path = find_batch_image(batch_id, image_name)
    if download:
        return FileResponse(path, media_type="image/tiff", filename=path.name)

    try:
        with Image.open(path) as image:
            image.thumbnail((1800, 1200), Image.Resampling.LANCZOS)
            preview = image.convert("RGB")
            output = BytesIO()
            preview.save(output, format="JPEG", quality=88, optimize=True)
    except OSError as error:
        raise HTTPException(500, f"Could not decode image {image_name}") from error

    return Response(
        content=output.getvalue(),
        media_type="image/jpeg",
        headers={"Cache-Control": "public, max-age=3600"},
    )


if __name__ == "__main__":
    import uvicorn
    # Running this module directly starts the local development API on port 8000.
    uvicorn.run(app, host="0.0.0.0", port=8000)